# Change these first
owner: HLOLIG # Your GitHub organization or username, where this repository lives
repo: upptime-v1.3 # The name of this repository

sites:
  - name: Blog
    url: https://blog.hloli.pw
    icon: https://blog.hloli.pw/melody-favicon.ico
    maxResponseTime: 5000
  - name: Google DNS 1
    check: "tcp-ping"
    url: $GOOGLE_DNS_1
    port: 53
  - name: US Server
    check: "tcp-ping"
    url: $US_SERVER
    port: 80
  - name: Uptime page
    url: $UPTIMEPAGE
  - name: Google
    url: https://www.google.com
    icon: https://www.google.com/favicon.ico
    expectedStatusCodes:
      - 200
      - 201
      - 404

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: uptime.hloli.pw
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/HLOLIG/upptime-v1.3/master/assets/upptime-icon.svg
  name: Hloli's Service Status
  introTitle: "**-**."
  introMessage: "-"
  navbar:
    - title: 运行状态
      href: /
    - title: 咕咕咕博客
      href: https://blog.hloli.pw

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
